version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'udbms_users'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=udbms_users'

  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: 'authorization-service'
    ports:
      - "8080:8080"
    depends_on: postgres