spring:
  datasource:
    url: jdbc:postgresql://dbinstances/instances
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  config: 'classpath:log4j2.yml'
server:
  port: 8084
