logging:
  config: 'classpath:log4j2.yml'
server:
  port: 1488
spring:
  config:
    import: file:databases.yml
  rabbitmq:
    consumer:
      exchange: query-executor-exchange
      request:
        queue: query-executor-queue
        routing-key: query-executor-routing-key
      response:
        queue-response: query-executor-queue-response
        routing-key-response: query-executor-routing-key-response

    username: guest
    password: guest
    ports:
      - "5672:5672"
      - "15672:15672"