FROM openjdk:17
EXPOSE 8080
ADD universal-database-management-system/Authorization-Service/target/authorization-service-0.0.1.jar authorization-service.jar
CMD ["java","-jar","authorization-service.jar"]
