name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  GITHUB_TOKEN: ${{ github.token }}
  AUTHORIZATION_SERVICE: authorization-service
  DATABASE-MANAGER: database-manager
  INSTANCE-MANAGER: instance-manager
  QUERY-EXECUTOR: query-executor
  TABLE-MANAGER: table-manager
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip
      
  push_to_cr:
    needs: build
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Docker-Compose Build
    - name: Push ${{env.AUTHORIZATION_SERVICE}} to GHCR
      run: |  
        docker-compose build
        docker tag ${{env.AUTHORIZATION_SERVICE}} ghcr.io/romekbulogin/${{env.AUTHORIZATION_SERVICE}}:latest
        docker push ghcr.io/romekbulogin/${{env.AUTHORIZATION_SERVICE}}:latest
        
    - name: Push ${{env.INSTANCE-MANAGER}} to GHCR
      run: |
        docker tag ${{env.INSTANCE-MANAGER}} ghcr.io/romekbulogin/${{env.INSTANCE-MANAGER}}:latest
        docker push ghcr.io/romekbulogin/${{env.INSTANCE-MANAGER}}:latest

    - name: Push ${{env.DATABASE-MANAGER}} to GHCR
      run: |
        docker tag ${{env.DATABASE-MANAGER}} ghcr.io/romekbulogin/${{env.DATABASE-MANAGER}}:latest
        docker push ghcr.io/romekbulogin/${{env.DATABASE-MANAGER}}:latest
