name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  AUTHORIZATION_SERVICE: authorization-service
  DATABASE-MANAGER: database-manager
  INSTANCE-MANAGER: instance-manager
  QUERY-EXECUTOR: query-executor
  TABLE-MANAGER: table-manager
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip

  push_to_cr:
    needs: build
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - uses: actions/checkout@v3

#      - name: Docker-Compose Build
#        run: docker-compose build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./Authorization-Service
          file: ./Dockerfile
          push: true
          tags: authorization-service ghcr.io/romekbulogin/authorization-service:latest

#      - name: Push $AUTHORIZATION_SERVICE to GHCR
#        run: |
#          docker tag $AUTHORIZATION_SERVICE ghcr.io/romekbulogin/$AUTHORIZATION_SERVICE:latest
#          docker push ghcr.io/romekbulogin/$AUTHORIZATION_SERVICE:latest

#      - name: Push $INSTANCE-MANAGER to GHCR
#        run: |
#          docker tag $INSTANCE-MANAGER ghcr.io/romekbulogin/$INSTANCE-MANAGER:latest
#          docker push ghcr.io/romekbulogin/$INSTANCE-MANAGER:latest
#
#      - name: Push $DATABASE-MANAGER to GHCR
#        run: |
#          docker tag $DATABASE-MANAGER ghcr.io/romekbulogin/$DATABASE-MANAGER:latest
#          docker push ghcr.io/romekbulogin/$DATABASE-MANAGER:latest
