name: Maven Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  AUTHORIZATION_SERVICE: authorization-service
  DATABASE_MANAGER: database-manager
  INSTANCE_MANAGER: instance-manager
  QUERY_EXECUTOR: query-executor
  TABLE_MANAGER: table-manager
jobs:
  Build_and_Push_to_GHCR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Docker-Compose Build
        run: docker compose build

      - name: Push $AUTHORIZATION_SERVICE to GHCR
        run: |
          docker tag $AUTHORIZATION_SERVICE ghcr.io/romekbulogin/$AUTHORIZATION_SERVICE:latest
          docker push ghcr.io/romekbulogin/$AUTHORIZATION_SERVICE:latest

      - name: Push $INSTANCE-MANAGER to GHCR
        run: |
          docker tag $INSTANCE-MANAGER ghcr.io/romekbulogin/$INSTANCE_MANAGER:latest
          docker push ghcr.io/romekbulogin/$INSTANCE_MANAGER:latest